data/meson.build
Default behavior of appstream util, while validating the appstream file, is to ensure that the URL referred to in the appstream file are reachable.
For downstream distribution (eg, in Debian), it is common practice that builds are network isolated and therefore this --nonet parameters helps with that requirement.
=> Avoid appstream util network connections during builds

src/meson.build
Helps meson install the module files where the system stores python
modules and not under /usr/share/portfolio/portfolio.
=> Install module files in the correct location

src/main.css, src/places.py
This will be OPTIONAL for the flatpak version, since
I prefer to give very few permissions by default. At
least until this app gets more testing in the wild.
If someone wants to enable this, use flatpak-override
or Flatseal, giving filesystem=host permission.
=> places: Add OS ROOT directory as System

src/window.py
At one point I considered this a feature, but it's better to  keep the behavior predictable as it was originally.
=> window: Don't activate last unselected row

src/window.py, src/window.ui
There's still not support for queueing operations so, for now, it's better to prevent clashes between operations.
=> menu: Disable options while on loading

src/window.py, src/worker.py
* If the source directory is different than the target directory it will override. A confirmation warning will be displayed.
* If the source directory is the same as the target, it will rename the copy, e.g. existing_file(1).
=> worker: Make copy smarter

src/main.css, src/window.py, src/window.ui
Portfolio always places folders on top (above files), and since folders are critical  for navigation, this button should come handy.
Closes #46
=> window: Add go to top button

src/window.py, src/worker.py
In some cases the OS report directories that doesn't exists,
or the user don't have the required permissions to read them,
in that case the call to 'os.listdir()' will fail with an
OSError.
This commits add a new event to the PorfolioLoadWorker that
is fired if the directory can't be listed.
This new event is handled and a message with a summary
is displayed to the user.
=> Show error message on dir listing error

src/utils.py, src/window.py, src/worker.py
Python  os.walk()  default behavior is to ignore permission errors, therefore, make sure we _do_ catch these errors and report these accordingly.
=> worker: Catch permissions errors while walking directory

src/window.py, src/window.ui, src/worker.py, tests/worker.py.in
This will provide much richer feedback to the user regarding the status of the just-opened file.
Closes #86
=> workers: Add PortfolioOpenWorker

src/worker.py, tests/window.py.in, tests/worker.py.in
Keep the  delete operations in the  main  thread
so that the main thread doesn't get spammed with
signals from the worker thread.
=> worker: Make delete feedback smoother

src/window.py, src/window.ui, src/worker.py, tests/worker.py.in
This mimics the "cancel" behavior seen in other file managers, e.g. nautilus. All  "progress"  made until the stop button was hit is kept.
=> worker: Support stopping paste and delete operations

data/dev.tchx84.Portfolio.desktop.in
Specify how to execute the application including options  related to mimetype support. 
The MimeType attribute is set in the desktop file so using this %f option declares what argument should be used.
Freedesktop standard reference: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables
Lintian warning raised on Debian side to identify this: https://lintian.debian.org/tags/desktop-mime-but-no-exec-code.html
=> Set the argument to be used wrt supported MimeType

src/window.py
When selecting an item and then clicking on a Place, e.g. Home the next tapped item would select instead of activating.
=> window: Set the proper selection mode after switching places

src/window.py
This is a regression caused by splitting _on_load_started
with the _delayed second step.
=> windows: Fix treeview going insensitive while loading

src/window.py
Now that we moved the places options to the home page
we need to safeguard against previous assumption that
$HOME was the home page.
=> windows: Fix missing history safeguard

src/places.py
get_user_special_dirs can return None if the logical id could not be
resolved, so this change handles this case by skipping over the call to
_add_place.
Without this check, the application will crash with a TypeError when it
ultimately calls os.fspath(None).
=> places: handle cases where XDG_ dirs couldn't be resolved

src/dev.tchx84.Portfolio.in, src/meson.build, src/places.py, src/translation.py, src/window.py, src/worker.py
Python built without gettext support (from glibc) fail here, so this
falls back to importing the gettext python implementation
(https://github.com/hannosch/python-gettext), which might
be available.
=> Fall back to gettext module on systems that don't use glibc

src/popup.py, src/window.py
If removing the device takes long,  it's likely that
the user won't stay looking at the popup transitions
so  it's better for the popup  to stay open for when
the user comes back.
=> popup: Don't close places popup automatically

src/window.py
The trash spec does not allow restoring or emptying trash folder sub-directories anyway. So it's better to not allow it in the first place.
Closes #198
=> trash: Disable restoring and emptying buttons on sub-directories

src/utils.py, src/worker.py
Calling fsync() does not necessarily ensure that the entry in the
directory containing the file has also reached disk.  For that an
explicit fsync() on a file descriptor for the directory is also
needed.
=> utils: Add sync_folder and sync all folder creation

src/window.py, src/worker.py
Previously, files were added to the view before the
actual  paste  operation ocurred.  If the operation
failed, the view would end up with ghost files.
=> worker: Update view only after paste operation

src/window.py, src/worker.py, tests/worker.py.in
This was being done on the UI thread, which causes some unncessary freezes.
=> worker: Move icon-loading step to the worker thread

src/files.py, src/files.ui, src/meson.build, src/portfolio.gresource.xml, src/window.py, src/window.ui, tests/window.py.in
=> files: Move the files viewer and selection  bits to a separate widget
