src/main.css, src/meson.build, src/placeholder.py, src/placeholder.ui, src/portfolio.gresource.xml, src/window.py
=> window: Display a placeholder on empty folders

src/main.css, src/popup.py, src/row.py, src/window.py, src/window.ui
=> window: Support copy and paste files

src/main.css, src/window.ui
=> menu: Align all items to the left

src/main.css, src/window.py, src/window.ui
=> about: Move it upwards and provide its own headerbar

data/dev.tchx84.Portfolio.desktop.in
Helps the users find the application from their shell menu using
keywords.
=> Desktop file: add keywords

data/dev.tchx84.Portfolio.metainfo.xml.in
=> data: Use a more descriptive app summary

src/main.css, src/window.py, src/window.ui
By adding a "Last Modified" option, it would cover the most common cases, e.g a download finished and it helps to find the downloaded file quicker.
Closes #50
=> menu: Add basic sorting options

src/__init__.py, src/window.py, src/worker.py
At this point, I likely don't  cover every possible error so I  don't  want to bother testers with having to touch the code or me having to provide patched builds.
=> logging: Add debug statements to all except clauses

src/places.py
=> places: Don't repeat default places

po/LINGUAS, po/cs.po
=> po: Add Czech translation

data/dev.tchx84.Portfolio.service.in, data/meson.build, dev.tchx84.Portfolio.json, meson_options.txt, src/main.py, src/meson.build, src/org.freedesktop.FileManager1.xml, src/portfolio.gresource.xml, src/service.py, src/window.py, src/worker.py, tests/meson.build, tests/service.py.in, tests/window.py.in
=> Support org.freedesktop.FileManager1 interface

po/POTFILES, po/portfolio.pot, src/main.css, src/main.py, src/service.py, src/window.py, src/window.ui, src/worker.py, tests/root/home/tchx84/file, tests/service.py.in, tests/worker.py.in
=> Add screen to display file properties

po/cs.po
=> po: Update Czech translation

src/worker.py
Gio.File.copy can be cancelled. This means we don't
need to wait for the  current  copy operation to be
completed to stop the copy operation.
Closes #105
=> worker: Use Gio.File.copy and Gio.Cancellable

src/main.css, src/main.py, src/places.py, src/window.py, src/window.ui
=> places: Support classic places

data/dev.tchx84.Portfolio.desktop.in
Add the text from AppStream metainfo summary as a comment to desktop file. This is not required, but as far as I know is recommended.
/cc @tchx84
=> data: Add Comment to the desktop file

src/window.py
=> window: Don't display loading screen if loaded fast enough

dev.tchx84.Portfolio.json, src/main.css, src/meson.build, src/place.py, src/place.ui, src/places.py, src/portfolio.gresource.xml
=> place: Support eject

src/places.py
=> places: Add shortcut to /run/host

dev.tchx84.Portfolio.json, src/places.py, src/popup.py, src/popup.ui, src/window.py, src/window.ui, src/worker.py, tests/worker.py.in
=> WIP: Support Trash

src/places.py, src/popup.py, src/window.py, src/window.ui
=> places: Add notification popup

src/utils.py, src/window.py, src/worker.py
* Move generic checks and utilities to the actual utils module
* Fix filtering.
* Fix searching.
=> trash: Misc fixes and refactors

src/window.py
=> window: Scroll the view to the just-left directory

data/dev.tchx84.Portfolio.gschema.xml, src/meson.build, src/settings.py, src/window.py, src/window.ui
=> settings: Persist user filter and sort options

src/trash.py
=> trash: Handle permissions-restricted mounts

src/trash.py, src/window.py
=> trash: Don't break when None mount_point or user_id

data/dev.tchx84.Portfolio.rules, src/devices.py, src/main.css, src/place.py, src/place.ui, src/places.py, src/window.py, src/window.ui
=> Support unlocking encrypted devices

src/devices.py
See http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-property-org-freedesktop-UDisks2-Block.HintSystem
Closes #245
=> devices: Ignore system devices

po/es.po
He hecho unos cambios para mejorar las cadenas "es" en monitores pequeños e incluyendo el cambio del nombre de la apl.
=> Mejoramiento del archivo es

src/utils.py, src/window.py, src/window.ui
=> Switch to regular icons

src/main.css, src/window.py, src/window.ui, src/worker.py
=> properties: Display file permissions

src/meson.build, src/placeholder.py, src/placeholder.ui, src/portfolio.gresource.xml, src/window.py, src/window.ui
=> placeholder: Move placeholder to separate widget

src/loading.py, src/loading.ui, src/meson.build, src/portfolio.gresource.xml, src/window.py, src/window.ui
=> loading: Move loading-related bits to a separate widget

README.md, dev.tchx84.Portfolio.json, src/about.ui, src/files.py, src/files.ui, src/loading.ui, src/main.py, src/menu.py, src/menu.ui, src/meson.build, src/passphrase.py, src/passphrase.ui, src/place.py, src/place.ui, src/placeholder.ui, src/places.py, src/popup.py, src/popup.ui, src/portfolio.gresource.xml, src/properties.ui, src/settings.py, src/style.css, src/utils.py, src/window.py, src/window.ui, tests/requirements.txt, tests/service.py.in, tests/window.py.in, tests/worker.py.in
=> Port to GTK 4

src/places.py, src/utils.py
=> places: Hide XDG directory if doesn't exist

po/LINGUAS, po/zh_CN.po
Add Chinese (simplified) translation.
=> po: Add Chinese (simplified) translation

po/LINGUAS, po/hi.po
This adds initial Hindi `hi` language translation.
Cheers.
=> Initial Hind translation

po/LINGUAS, po/ar.po
This adds Arabic translation.
Please note that I transliterated the name of the app due to RTL issues, other GNOME apps tend to do this too.
=> po: Add Arabic translation

data/dev.tchx84.Portfolio.metainfo.xml.in
Add launchable, vcs-browser url and translate url tags.
Cherry-picked from https://github.com/flathub/dev.tchx84.Portfolio/pull/19.
Also add a developer tag.
=> Update AppStream metadata
